name: Discord Bot Event Scraping

on:
  schedule:
    # Run daily at 12 PM UTC (adjust timezone as needed)
    - cron: '0 12 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  discord-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Discord Bot
      env:
        LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        TICKETMASTER_API_KEY: ${{ secrets.TICKETMASTER_API_KEY }}
        BANDSINTOWN_APP_ID: ${{ secrets.BANDSINTOWN_APP_ID }}
        LASTFM_USERS: ${{ secrets.LASTFM_USERS }}
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
      run: |
        python run_discord_bot.py
