name: Event Scraping (No Discord)

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  scrape-events:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      env:
        LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        TICKETMASTER_API_KEY: ${{ secrets.TICKETMASTER_API_KEY }}
        BANDSINTOWN_APP_ID: ${{ secrets.BANDSINTOWN_APP_ID }}
        LASTFM_USERS: ${{ secrets.LASTFM_USERS }}
      run: python main.py

